---
name: Build containers
on:
  push:
    branches:
      - main
    # paths:
    #  - 'release-versions/*'

env:
  GITLAB_CONTAINER_BASE_URI: registry.gitlab.com/patrickdung/docker-images/goatcounter
jobs:
  build-docker-image:
    name: Build Docker Images
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      # GH action/scanners for sarif reports
      security-events: write
      statuses: none
      # id-token: write # needed for signing the images with GitHub OIDC **not production ready**
    outputs:
      remote_branch_name: ${{ steps.get-remote-branch-name.outputs.remote_branch_name }}
      gitlab_container_base_uri: ${{ steps.set-outputs.outputs.gitlab_container_base_uri }}
      container_digest_amd64: ${{ steps.get-container-digest-amd64.outputs.container_digest }}
      container_digest_arm64: ${{ steps.get-container-digest-arm64.outputs.container_digest }}
    steps:
      - name: Set outputs for this job
        id: set-outputs
        run: |
          echo "::set-output name=gitlab_container_base_uri::$(echo $GITLAB_CONTAINER_BASE_URI)"

      - name: Fetch branch name (tag) of latest release
        id: get-remote-branch-name
        run: |
          curl -sL https://api.github.com/repos/arp242/goatcounter/releases/latest | \
          jq -r ".tag_name" > /tmp/goatcounter-latest-branch-name
          echo "REMOTE_BRANCH_NAME=$(cat /tmp/goatcounter-latest-branch-name)" >> $GITHUB_ENV
          echo "::set-output name=remote_branch_name::$(cat /tmp/goatcounter-latest-branch-name)"

      - name: Checkout repository (to get Dockerfile for building)
        uses: actions/checkout@v2
        with:
          # repository: patrickdung/goatcounter-container
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry provider
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Install Cosign GH action
        uses: sigstore/cosign-installer@main
        # with:
        #  cosign-release: 'v1.4.1'

      - name: Build and push to container registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ##  ARCH=${{ env.TO_BE_FIXED }}
            RELEASE_VERSION=${{ env.REMOTE_BRANCH_NAME }}
          platforms: linux/amd64,linux/arm64
          push: true
            # #registry.gitlab.com/patrickdung/docker-images/goatcounter:latest
            # registry.gitlab.com/patrickdung/docker-images/goatcounter:${{ env.REMOTE_BRANCH_NAME }}
          tags: |
            ${{env.GITLAB_CONTAINER_BASE_URI}}:${{ env.REMOTE_BRANCH_NAME }}

      - name: "Get the digest of container (amd64)"
        id: get-container-digest-amd64
        run: |
          skopeo inspect --raw docker://${{env.GITLAB_CONTAINER_BASE_URI}}:${{env.REMOTE_BRANCH_NAME}} | \
            jq -r '.manifests[] | select(.platform .architecture=="amd64" and .platform .os=="linux") | .digest' > /tmp/container-digest-amd64
          echo "::set-output name=container_digest::$(cat /tmp/container-digest-amd64)"

      - name: "Get the digest of container (arm64)"
        id: get-container-digest-arm64
        run: |
          skopeo inspect --raw docker://${{env.GITLAB_CONTAINER_BASE_URI}}:${{env.REMOTE_BRANCH_NAME}} | \
            jq -r '.manifests[] | select(.platform .architecture=="arm64" and .platform .os=="linux") | .digest' > /tmp/container-digest-arm64
          echo "::set-output name=container_digest::$(cat /tmp/container-digest-arm64)"

      - name: Use Cosign to sign the image recursively
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          ## CONTAINER_IMAGE="${{env.GITLAB_CONTAINER_BASE_URI}}:${{ env.REMOTE_BRANCH_NAME }}"
          # Sign the multiarch images, the signature is also pushed to the registry
          cosign sign --recursive --key ./cosign.key "${{env.GITLAB_CONTAINER_BASE_URI}}:${{ env.REMOTE_BRANCH_NAME }}"

  build-sbom-and-scanning:
    needs: [build-docker-image]
    name: Build SBOM and image scanning
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      # GH action/scanners for sarif reports
      security-events: write
      statuses: none
      # id-token: write # needed for signing the images with GitHub OIDC **not production ready**
    strategy:
      # Anchore action produce the same filename for sarif on different platform
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform_image_uri: "${{needs.build-docker-image.outputs.gitlab_container_base_uri}}@${{ needs.build-docker-image.outputs.container_digest_amd64 }}"
          - arch: arm64
            platform_image_uri: "${{needs.build-docker-image.outputs.gitlab_container_base_uri}}@${{ needs.build-docker-image.outputs.container_digest_arm64 }}"
    steps:

      - name: Set env REMOTE_BRANCH_NAME
        run: |
          echo "REMOTE_BRANCH_NAME=${{ needs.build-docker-image.outputs.remote_branch_name }}" >> $GITHUB_ENV

      - name: Login to Registry provider
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Install Cosign GH action
        uses: sigstore/cosign-installer@main
        # with:
        #  cosign-release: 'v1.4.1'

      - name: "Fetch branch name of latest release versions Other software"
        run: |
          curl -sL https://api.github.com/repos/anchore/syft/releases | \
            jq -r ".[].tag_name" | grep -v rc | sort -nr -t. -k 1 -k 2 -k 3 | head -n 1 | sed -E 's|^v||' > /tmp/syft-latest-branch-name
          echo "SYFT_VERSION=$(cat /tmp/syft-latest-branch-name)" >> $GITHUB_ENV
          curl -sL https://api.github.com/repos/anchore/grype/releases | \
            jq -r ".[].tag_name" | grep -v rc | sort -nr -t. -k 1 -k 2 -k 3 | head -n 1 | sed -E 's|^v||' > /tmp/grype-latest-branch-name
          echo "GRYPE_VERSION=$(cat /tmp/grype-latest-branch-name)" >> $GITHUB_ENV

      - name: Install Syft
        run: |
          cd /tmp
          curl -L -O -v https://github.com/anchore/syft/releases/download/v${{env.SYFT_VERSION}}/syft_${{env.SYFT_VERSION}}_linux_amd64.deb
          curl -L -O -v https://github.com/anchore/syft/releases/download/v${{env.SYFT_VERSION}}/syft_${{env.SYFT_VERSION}}_checksums.txt
          sha256sum -c syft_${{env.SYFT_VERSION}}_checksums.txt --ignore-missing
          sudo dpkg -i syft_${{env.SYFT_VERSION}}_linux_amd64.deb

      - name: Set the SBOM env variable for use by later steps
        run: |
          echo "ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT=container-sbom.json" >> $GITHUB_ENV

      - name: Use Syft to generate the SBOM files
        run: |
          ## syft -v "registry.gitlab.com/patrickdung/docker-images/meilisearch:${{ env.REMOTE_BRANCH_NAME }}" -o json > ./${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
          syft -v ${{matrix.platform_image_uri}} -o json > ./${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}

      - name: Upload SBOM files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PUBLISH_TOKEN }}
          file: ./*${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
          file_glob: true
          tag: ${{ env.REMOTE_BRANCH_NAME }}
          overwrite: true

      # Cannot download if it's not generated as artifact
      # - name: Download the container SBOM artifact
      #  uses: actions/download-artifact@v2
      #  with:
      #    #name: container-sbom.spdx.json
      #    name: ${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}

      - name: Create SBOM attestation
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
          # ##SBOM_FILE: ./container-sbom.spdx.json
          # ##SBOM_FILE: ${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          # CONTAINER_IMAGE=${{matrix.platform_image_uri}}
          # Create SBOM attestation and push it to the container registry
          # ##cosign attest --predicate "$SBOM_FILE" --key ./cosign.key "$CONTAINER_IMAGE"
          cosign attest --predicate "${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}" --key ./cosign.key "${{matrix.platform_image_uri}}"

      - name: Install Grype
        run: |
          cd /tmp
          curl -L -O -v https://github.com/anchore/grype/releases/download/v${{env.GRYPE_VERSION}}/grype_${{env.GRYPE_VERSION}}_linux_amd64.deb
          curl -L -O -v https://github.com/anchore/grype/releases/download/v${{env.GRYPE_VERSION}}/grype_${{env.GRYPE_VERSION}}_checksums.txt
          sha256sum -c grype_${{env.GRYPE_VERSION}}_checksums.txt --ignore-missing
          sudo dpkg -i grype_${{env.GRYPE_VERSION}}_linux_amd64.deb

      - name: Scan container by Grype
        run: |
          # May set a severity threshold for failing the build
          grype sbom:./${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}} -o json > ./${{matrix.arch}}-vulnerabilities-report-grype.json
          grype sbom:./${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}} -o table > ./${{matrix.arch}}-vulnerabilities-report-grype-table.txt

      - name: Upload Grype reports to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./*vulnerabilities-report-grype*
          name: "Vulnerabilities reports by Grype"

      - name: Upload Grype reports to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PUBLISH_TOKEN }}
          file: ./*vulnerabilities-report-grype*
          file_glob: true
          tag: ${{ env.REMOTE_BRANCH_NAME }}
          overwrite: true

      - name: Scan container with Trivy
        uses: aquasecurity/trivy-action@master
        id: scan-by-trivy
        with:
          image-ref: '${{matrix.platform_image_uri}}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: '${{matrix.arch}}-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: '${{matrix.arch}}-trivy-results.sarif'
          category: trivy-${{matrix.arch}}

      - name: Scan container by Anchore
        uses: anchore/scan-action@v3
        # ## id: scan-by-anchore-${{matrix.arch}}
        id: scan-by-anchore
        with:
          fail-build: false
          image: "${{matrix.platform_image_uri}}"
          acs-report-enable: true

      - name: Rename results.sarif with architecture name
        run: |
          mv results.sarif ${{matrix.arch}}-anchore-results.sarif

      - name: Upload Anchore SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          # the steps outputs would contain './'
          # ##sarif_file: ${{matrix.arch}}-${{ steps.scan-by-anchore-${{matrix.arch}}.outputs.sarif }}
          # sarif_file: anchore-${{matrix.arch}}-${{ steps.scan-by-anchore.outputs.sarif }}
          sarif_file: ./${{matrix.arch}}-anchore-results.sarif
          category: anchore-${{matrix.arch}}

      - name: Inspect SARIF report(s)
        run: |
          echo ${{matrix.arch}}
          cat ${{matrix.arch}}-trivy-results.sarif
          cat ${{matrix.arch}}-anchore-results.sarif

      - name: Upload SARIF reports to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "SARIF reports when containers are built"
          path: |
            # #${{matrix.arch}}-trivy-results.sarif
            # #${{ steps.scan-by-anchore.outputs.sarif }}
            ./*.sarif

      - name: Add the latest tag to the container image
        run: |
          skopeo copy --all docker://${{env.GITLAB_CONTAINER_BASE_URI}}:${{env.REMOTE_BRANCH_NAME}} docker://${{env.GITLAB_CONTAINER_BASE_URI}}:latest
