---
name: Built containers
on:
  push:
    branches:
      - main
    # paths:
    #  - 'release-versions/*'

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Fetch branch name (tag) of latest release
        run: |
          curl -sL https://api.github.com/repos/arp242/goatcounter/releases/latest | \
          jq -r ".tag_name" > /tmp/goatcounter-latest-branch-name
          echo "REMOTE_BRANCH_NAME=$(cat /tmp/goatcounter-latest-branch-name)" >> $GITHUB_ENV

      - name: Checkout repository (to get Dockerfile for building)
        uses: actions/checkout@v2
        with:
          # repository: patrickdung/goatcounter-container
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry provider
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ##  ARCH=${{ env.TO_BE_FIXED }}
            RELEASE_VERSION=${{ env.REMOTE_BRANCH_NAME }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.gitlab.com/patrickdung/docker-images/goatcounter:${{ env.REMOTE_BRANCH_NAME }}
